server:
  port: 8082

spring:
  application:
    name: parking-lot-design

  datasource:
    url: jdbc:postgresql://localhost:5434/ParkingLot
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Jjh123123!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

logging:
  level:
    root: INFO
    com.parking: DEBUG

